# Generated by Django 5.1.4 on 2025-02-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='Без коментаря'),
        ),
    ]
