# Generated by Django 5.1.4 on 2025-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('Зоология', 'Зоология'), ('Ботаника', 'Ботаника'), ('Анатомия людини', 'Анатомия людини'), ('Еволюція', 'Еволюція'), ('Генетика', 'Генетика')], default='Зоология', max_length=100),
        ),
    ]
