# Generated by Django 5.1.4 on 2025-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Botanics', 'Ботаніка'), ('Zoology', 'Зоологія'), ('Anatomy', 'Анатомія')], default='Botanics', max_length=50),
            preserve_default=False,
        ),
    ]
