# Generated by Django 5.1.4 on 2025-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('5 клас', '5 клас'), ('6 клас', '6 клас'), ('7 клас', '7 клас'), ('8 клас', '8 клас'), ('9 клас', '9 клас'), ('10 клас', '10 клас'), ('11 клас', '11 клас'), ('Загальне', 'Загальне'), ('Виховання', 'Виховання')], max_length=50, null=True),
        ),
    ]
