# Generated by Django 5.1.4 on 2025-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description2',
            field=models.TextField(default='По умолчанию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Виберіть категорію'), ('5 клас', '5 клас'), ('6 клас', '6 клас'), ('7 клас', '7 клас'), ('8 клас', '8 клас'), ('9 клас', '9 клас'), ('10 клас', '10 клас'), ('11 клас', '11 клас'), ('Загальне', 'Загальне'), ('Виховання', 'Виховання')], max_length=50, null=True),
        ),
    ]
