# Generated by Django 5.1.4 on 2025-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('Зоология', 'Зоология'), ('Ботаника', 'Ботаника'), ('Анатомия людини', 'Анатомия людини'), ('Еволюція', 'Еволюція'), ('Генетика', 'Генетика')], default='Зоологія', max_length=100),
            preserve_default=False,
        ),
    ]
