# Generated by Django 5.1.4 on 2025-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('Зоологія', 'Зоологія'), ('Ботаніка', 'Ботаніка'), ('Анатомія людини', 'Анатомія людини'), ('Еволюція', 'Еволюція'), ('Генетіка', 'Генетіка')], default='Зоология', max_length=100),
        ),
    ]
