# Generated by Django 5.1.4 on 2025-02-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
    ]
